### ISSUE TITLE
pypi (pip installable) package name

### ISSUE THREAD

**Issue by tom-f-oconnell** [FlySorterLLC/SantaFeControlSoftware#17]
It would be nice to package this software and make it pip installable.  One issue is that a package named `maple` already exists:
https://pypi.org/project/maple/

Thoughts an alternate name for a package?

I have some light experience packaging for pypi, so I could help you guys get it into a package once you settle on a name.

Edit: maplebot?

**Comment by flysorter** [comment]
Conferred with the team: let's go with MAPLErobot, pls.
